;; Owners of things
(define nic "Nic Marshall")
(define matt "Matthew Venn")
(define anton "Anton Bowers")
(define lauren "Lauren Simms")
(define unknown "UNKNOWN")
(define johnh "John Honnibal")
(define harry "Harry Gee")
(define barney "Barney Livingstone")
(define ians "Ian Stratford")
(define reprap-team "Ian Stratford / Russell Dicken")
(define hs #f)

;; locations of things
(define g10 "G10 (messy room)")
(define g11 "G11 (main room)")

;; things
(define all-things (list
  (make-thing* 'nics-table-saw "Table saw" nic #f #t g10 "Keep your hands away from the blade!")
  (make-thing 'vices "Wood and Metal Vices" hs #f #f g10)
  (make-thing 'nics-disk-sander "Disk sander" nic #f #t g10)
  (make-thing* 'pillar-drill "Pillar drill" hs #f #t g10 "Do not leave key in chuck!")
  (make-thing* 'bench-grinder "Bench grinder" hs #f #t g10 "Wear gloves and goggles!")
  (make-thing* 'belt-sander "Belt sander" hs #f #t g10 "Wear gloves and goggles!")
  (make-thing* 'bandsaw "Bandsaw" hs #f #t g10 "Keep your hands away from the blade!")
  (make-thing* 'woodturning_lathe "Wood lathe" anton #f #t g10 "Beware loose clothing and hair\nSpin by hand to ensure workpiece is secure.")
  (make-thing* 'laser_cutter "Epilog Laser Cutter" lauren #f #t g10 "See printed checklist and instructions.")
  (make-thing* 'myford_super_7_lathe "Metal lathe" matt #f #t g10 "Beware loose clothing and hair\nSpin by hand to ensure workpiece is secure.")
  (make-thing* 'cnc_milling_machine "CNC Router" matt #f #t g10 "Wear eye protection.\nMay move suddenly.")
  (make-thing* 'cnc_mill "CNC Mill" matt #f #t g10 "Wear eye protection.\nMay move suddenly.")

  (make-thing 'sewing-machine "Sewing machine" hs #f #t g11)
  (make-thing 'hp-designjet-500 "HP DesignJet 500" nic #f #t g11)
  (make-thing 'roland-dpx-3300 "Flatbed Plotter" hs johnh #t g11)
  (make-thing* 'uv-exposer "UV exposer" hs #f #t g11 "Don't look into the light!")
;;  (make-thing* 'harrys-laser "Laser Cutter" harry #f #t g11 "*** NOT FOR GENERAL USE ***")
  (make-thing* 'reprap "RepRap + Kinect" hs reprap-team #t g11 "CAUTION: Hot!")
  (make-thing 'magnifier-lamp "Magnifier Lamp" hs #f #f g11)
  (make-thing* 'irc-mac "IRC Mac" hs barney #f g11 "'mac_in_space' in #bristolhackspace")
  (make-thing 'pc "Hackspace PC" hs #f #f g11)
  (make-thing 'oscilloscope "Oscilloscope" hs #f #f g11)
  (make-thing* 'hot-air-gun "Hot air gun" hs #f #f g11 "CAUTION: HOT!!!")
  (make-thing 'sig-gens "Signal Generators" hs #f #f g11)
  (make-thing* 'bubble-etch "Bubble Etch Tank" hs #f #t g11 "CAUTION: CORROSIVE CHEMICALS\nWear gloves and goggles!")
  (make-thing* 'reflow-oven "Solder Reflow Oven" ians #f #f g11 "CAUTION: HOT!!!")

  (make-thing 'multimeters "Multimeters" hs #f #f g11)
  (make-thing 'label-printer "Label printer" hs #f #f g11)
  (make-thing 'psus "Power Supplies" hs #f #f g11)
  (make-thing 'dummy-load "Dummy Load" hs #f #f g11)
  (make-thing 'soldering-irons "Soldering irons" hs #f #f g11)
  (make-thing '20x-microscope "20x microscope" hs #f #f g11)
  (make-thing 'breadboards "Breadboards" hs #f #f g11)
  (make-thing 'hand-tools "General hand tools" hs #f #f g11)
  (make-thing 'bbc-micros "BBC Micros" hs #f #f g11)
  ))
